version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  ignore:
    # ignore Maven APIs/SPIs
    - dependency-name: org.apache.maven:*
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: "npm"
  directory: "/src/main/frontend/"
  schedule:
    interval: monthly
  groups:
    npm-all:
      applies-to: version-updates
      patterns:
        - "*"
